--- # dev infrastructure clone - agentebtc
- hosts: all
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  tasks:
  - name: Install NginX service
    apt:
            name: nginx
            state: latest
    notify:
    - enable and restart nginx service
  handlers:
  - name: enable and restart nginx service
    service:
            name: nginx
            enabled: yes
            state: restarted
  - name: Install Git
    apt:
            name: git
            state: latest
            update_cache: yes
  - name: Install python
    apt:
            name: pip
            state: latest