--- # Infrastructure demo YAML 2nd - install nginx on debian
- hosts: debian
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  tasks:
  - name: Install nginx service with latest service
    apt:
            name: nginx
            state: latest
    notify:
    - enable and restart nginx service
    register: output
  - name: Install git
    apt:
            name: git
            state: latest
  
  - debug: var=output
  handlers:
  - name: enable and restart nginx service
    service:
            name: nginx
            enabled: yes
            state: restarted
