--- # Infrastructure demo YAML 2nd - install nginx on debian
- hosts: debian
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  tasks:
<<<<<<< HEAD
  - name: Install NginX service on all instances that belong to debian group
=======
  - name: Install nginx service with latest service
>>>>>>> 57101c2... modifying debug playbook to force conflicts
    apt:
            name: nginx
            state: latest
    notify:
    - enable and restart nginx service
    register: output
  - debug: var=output
  handlers:
  - name: enable and restart nginx service
    service:
            name: nginx
            enabled: yes
            state: restarted
