- name: Install Packages
  apt: 
    name={{ item }} update_cache=yes state=latest
  with_items:
    - nginx
    - git
    - pip
    - vim
    - build-essential
    - npm
    - mcrypt
    - curl
    - nodejs