--- # dev infrastructure clone - agentebtc
- hosts: all
  #remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  roles:
  - { role: inst-servs }
  tasks:
  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted